# This is a basic workflow to help you get started with Actions

name: test_homework_CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@something
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: show dir homeworks
        run: 
          find . -maxdepth 1 -name "homework??" -type d
      - name: Test with Maven
        run: |
          dir_homework=$(find . -maxdepth 1 -name "homework??" -type d)
          cd $dir_homework
          mvn test
